name: Latest Linkedin posts
on:
  schedule: # Run workflow automatically
    - cron: '0 0 * * *' # Runs every day
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme-with-linkedin:
    name: Update this repo's README with latest linkedin posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
        max_post_count: "3"
        comment_tag_name: "LINKEDIN"
          feed_list: "https://www.linkedin.com/in/maksym-sydiaka-25985424a/recent-activity/all/"