name: Latest Linkedin posts
on:
  schedule:
    # Runs every day
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-youtube:
    name: Update this repo's README with latest linkedin posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "3"
          comment_tag_name: "LINKEDIN"
          feed_list: "https://www.linkedin.com/in/maksym-sydiaka-25985424a/recent-activity/all/rss.xml"
